Make observer pattern using lua
nic-dgl104-winter-2024/pattern-library pull request #74
Opened 2024-03-23 08:33 UTC by monika-789

2024-03-25 17:19 UTC, Bhoomi3637 commented
Can you please add a comment for better understanding?

2024-03-26 19:04 UTC, Dhuds1 requested changes
I think your code is well defined and readable, but I have a few suggestions! The main suggestion is to add more inline comments to the top of your methods, just to describe the indented behaviour of said method. Although it may be obvious to some, if not most people, this resource is intended to help introduce people to this pattern and it would be handy to add some small explanations of what happens when the method is called!

2024-03-26 19:04 UTC, Dhuds1 commented on patterns/Behavioral/Observal/Lua/monika.lua
> +print("Hello World!")-- Subject class
Hello World is the class subject? I'm only joking, just the way the comment has been added seems like you're talking about the print statement! You should maybe remove the print() for the final push of the code?

2024-03-26 19:04 UTC, Dhuds1 commented on patterns/Behavioral/Observal/Lua/monika.lua
> +end
How is this score function intended? As the type of game that you're representing isn't specified, which is fine, I'm not sure if the message being displayed is a personal message, or a broadcasted announcement. If it is a broadcasted announcement, it would be a good idea to add the `subjects` name to the `update message`, to read something like: `Player One's score has been update: 23`

This highly depends on the game type, but may be worth considering!

2024-03-26 19:20 UTC, ash-teach requested changes

2024-03-26 19:20 UTC, ash-teach commented on patterns/Behavioral/Observal/Lua/monika.lua
> +print("Hello World!")-- Subject class
Yes, I don't think this `print` is necessary here.

2024-03-26 19:20 UTC, ash-teach commented on patterns/Behavioral/Observal/Lua/monika.lua
> +GameSubject.__index = GameSubject
It's been a long time since I've used Lua regularly, but I wonder about the use of `__index` here. I guess you're setting up your `GameSubject` as a metatable directly?

I think this needs more explanation.

2024-03-26 19:20 UTC, ash-teach commented on patterns/Behavioral/Observal/Lua/monika.lua
> +        observer:updateScore(self.score)
`notify` should not have a direct dependency on `updateScore` - what if there are other types of notification you would like to provide? Instead `notify` should probably be called on a state update and should reflect the state changes, which may eventually call `updateScore` in turn.

2024-03-26 19:20 UTC, ash-teach commented on patterns/Behavioral/Observal/Lua/monika.lua
> +game:setScore(300)
The comments you have provided here are helpful - consider adding more comments like these to the implementations above.

2024-03-26 19:22 UTC, ash-teach commented
@monika-789 - thanks for your work on this. I think more clarification is needed in describing the approach you've taken. In particular, there are no comments in the implementation section. Can you read through the review comments and address, please?

Also - if you have used any external resources in constructing this example please include links in header comments at the top of the file.

2024-03-26 19:28 UTC, monika-789 commented
Thank you for the feedback. I will check every detail according to the feedback and try to change it, to make it more perfect and understandable.

2024-03-26 23:53 UTC, monika-789 commented on patterns/Behavioral/Observal/Lua/monika.lua
> +print("Hello World!")-- Subject class
@Dhuds1 Thank you for pointing out this error. I was using the online compiler then I just copied and pasted the code as it was in the Hello World program.
I will remove this.

2024-03-27 22:12 UTC, monika-789 commented on patterns/Behavioral/Observal/Lua/monika.lua
> +GameSubject.__index = GameSubject
@ash-teach Certainly, I will explain the use of __index in Lua, Actually __index is like a backup plan for tables. If Lua can't find something directly in a table, it checks if there's a backup table assigned to __index to search for it there.

2024-04-15 16:08 UTC, merged