Factory design patterns
nic-dgl104-winter-2024/pattern-library pull request #77
Opened 2024-03-24 20:02 UTC by nazrinzuwair

Hi @ash-teach ,

I've created PR#26. Here's what I've accomplished regarding the Factory Design Pattern:

Created a folder named "Factory-Design-Pattern" inside the PATTERN-LIBRARY. It includes README.md and factory-method.js files.

The README.md file contains a brief summary of implementing the Factory Design Pattern in JavaScript using the factory design method. It includes a code snippet example related to "Creating Foods". Additionally, I've listed additional programming languages where the Factory Design Pattern can be implemented, along with corresponding website links.

Also, I've created a file named factory-method.js, which contains the entire code snippet mentioned in the README.md.

Added a reference section in the README.md with links to the websites I browsed during my research.

2024-03-25 19:40 UTC, nazrinzuwair commented
@ash-teach  Could you please review this.

2024-03-26 06:31 UTC, kattsky commented
Hi @nazrinzuwair I've reviewed your code, and overall, it's very well-structured and maintains good object-oriented principles. I also like to commend your detailed documentation of your implementation that made it easy to grasp the goal and functionality of the facade pattern.

Building upon the foundation of a well-documented code, one aspect to consider exploring to enhance flexibility is create instances of the subsystem classes outside of the `SoftwareFacade` class,.

As an alternative to creating instances of `SoftwareDeveloper`, `Designer`, and `DatabaseEngineer` within the `SoftwareFacade` constructor, these can be passed as parameters. The benefit of creating instances of the subsystem classes externally rather than internal implementation helps `SoftwareFacade` object (being the mediator between the client code and the subsystem classes) to access them in the software development process which aligns with facade pattern's goal to provide simplified interface to a complex system.

:raised_hands: Fantastic work, @nazrinzuwair

2024-03-26 19:24 UTC, nazrinzuwair commented
Thanks for your feedback @kattsky :)

2024-03-26 23:38 UTC, ash-teach requested changes

2024-03-26 23:38 UTC, ash-teach commented on patterns/Facade-Pattern/README.md
> +
Any time you reference code in a sentence or paragraph you can use in-line code markdown (i.e. single backticks) to denote that you are referring to code. For example, the paragraph above should be styled as follows:

We have three classes here: `SoftwareDeveloper`, `Designer`, and `DatabaseEngineer`, each of which represents a subsystem responsible for a specific task in the software development process. The `SoftwareDeveloper` class's `code()`method takes handle of coding activities, the `Designer` class's `design()` method takes responsibility of designing tasks, and the `DatabaseEngineer` class's `connect()` method takes charge of database connection tasks. Each subsystem's behavior is specified by these classes.

2024-03-26 23:38 UTC, ash-teach commented on patterns/Facade-Pattern/README.md
> +
Oh! I see you've done that below - you must have just missed this paragraph.

2024-03-26 23:38 UTC, ash-teach commented on patterns/Factory-Design-Patten/README.md
> +
Did you intended to style the above paragraph all in **bold** and not part of the list with Creator and Concrete Product?  This just seems like an odd styling choice, and I'm not sure what you intend to communicate by it.

2024-03-26 23:38 UTC, ash-teach commented on patterns/Factory-Design-Patten/README.md
> +
As with the comment above - please make sure all inline reference to code in sentences or paragraphs are appropriately styled with single backticks.

2024-03-26 23:38 UTC, ash-teach commented on patterns/Factory-Design-Patten/README.md
> +        }
Maybe a [switch statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch) is a semantic improvement here?

2024-03-26 23:38 UTC, ash-teach commented on patterns/Factory-Design-Patten/README.md
> +    this.famousAudience = "youngers!";
"young**sters**!" :)

2024-03-26 23:38 UTC, ash-teach commented on patterns/Factory-Design-Patten/README.md
> +
While I appreciate your inclusion of these details in each food paragraph, I think you could have one paragraph to list the benefits attributable to all three classes, and remove the paragraphs for each food. That will cut down on unnecessary repetition.

2024-03-26 23:43 UTC, ash-teach commented
Great work, @nazrinzuwair! Very well documented and structured. I have very few comments, other than primarily some styling related notes. Though I do want to highlight @kattsky's comment as valid (quoted below), and worth considering.

> As an alternative to creating instances of `SoftwareDeveloper`, `Designer`, and `DatabaseEngineer` within the `SoftwareFacade` constructor, these can be passed as parameters. The benefit of creating instances of the subsystem classes externally rather than internal implementation helps `SoftwareFacade` object (being the mediator between the client code and the subsystem classes) to access them in the software development process which aligns with facade pattern's goal to provide simplified interface to a complex system.

As a further note, I would normally suggest that you do not need to reproduce all code as part of your documentation (the user can easily visit the actual code afterall). However, in this case, you've done such a great job of discussing the code, I would prefer to leave it as-is. Fantastic work!

2024-03-27 05:27 UTC, nazrinzuwair commented
Hi @kattsky and @ash-teach 
Thanks for your valuable feedback. I have made the changes and it is ready for your review. 
Thank You!

2024-03-27 06:46 UTC, kattsky commented
Thanks for catching those details, @nazrinzuwair. Got nothing else to add from my end.

2024-04-15 16:11 UTC, merged