Add defination of Strategy pattern
nic-dgl104-winter-2024/pattern-library pull request #84
Opened 2024-03-25 19:05 UTC by jaskaransingh9990

2024-03-26 06:33 UTC, BasranS commented
Your work seems good! Just a suggestion to add some examples or scenarios, which could enhance the understandability of the topic well.

2024-03-26 21:36 UTC, jaskaransingh9990 commented
hey @BasranS  your idea  seems good. i see want can i add thanks

2024-04-02 21:21 UTC, ash-teach requested changes

2024-04-02 21:21 UTC, ash-teach commented on README.md
> +* Flexibility and Extensibility:
Remove the colon at the end of this bullet

2024-04-02 21:21 UTC, ash-teach commented on README.md
> +* Easy to  Maintenance
"Easy to maintain"

2024-04-02 21:21 UTC, ash-teach commented on README.md
> + * Cash:
I don't think you've done quite enough in this example. It doesn't quite help make sense of Strategy.

2024-04-02 21:21 UTC, ash-teach commented on README.md
> +* Privacy: The confidentiality of personal financial information and transaction details.
I don't understand how these bullet points are related to Strategy pattern.

2024-04-02 21:23 UTC, ash-teach commented
Thanks for adding this, @jaskaransingh9990. Your example doesn't quite do enough to help explain Strategy: The setup is there (payment choice between Credit, Debit or Cash) but you haven't described how the Strategy pattern helps in this case. Please review and update the PR. Also, there are some typos to be fixed.

2024-04-15 17:52 UTC, ash-teach commented
Hm. The changes made don't really address the issue. The overview you've provided is good, but you had some examples that weren't clearly connected with the overview. Removing these and adding code without comment doesn't improve the situation for novices.

2024-04-15 17:55 UTC, merged

2024-04-15 17:55 UTC, ash-teach commented
I've removed the code example, since it doesn't really belong in the main README either.