Implement observer pattern in react native
nic-dgl104-winter-2024/pattern-library pull request #85
Opened 2024-03-25 20:41 UTC by Suhail0206327

2024-03-27 14:37 UTC, Anjitha-94 commented
@Suhail0206327  Your code is neat and clean, it is better if you had more comments for the code for a better understanding

2024-04-02 22:04 UTC, ash-teach requested changes

2024-04-02 22:04 UTC, ash-teach commented on .expo/README.md
> +No, you should not share the ".expo" folder. It does not contain any information that is relevant for other developers working on the project, it is specific to your machine.
It seems like perhaps you didn't want to commit this folder.

2024-04-02 22:04 UTC, ash-teach commented on CONTRIBUTING.md
> +this is the link to my forked repository
Not sure if you intentionally blew away the existing CONTRIBUTING.md doc - looks like you've tried to commit the CONTRIBUTING.md that should be in your research and reflection journal.

2024-04-02 22:04 UTC, ash-teach commented on README.md
> +Here I am solving two issues
As above with CONTRIBUTING.md - you've deleted all the existing work in the README.md file with this commit. I don't think this is your intent, so perhaps this statement about solving two issues belongs elsewhere?

2024-04-02 22:04 UTC, ash-teach commented on journals/.gitignore
> +*.tsbuildinfo
In general, I don't think this .gitignore is going to work as intended in the /journals folder. This .gitignore reads like a root .gitignore file (i.e. it's presented directory paths from root, rather than from /journal).

2024-04-02 22:04 UTC, ash-teach commented on CandyFactory.java
> +}
Without any documentation, I'm not sure what this is.

2024-04-02 22:04 UTC, ash-teach commented on journals/app.json
> +}
Is it possible to complete the necessary setup of this example using npm? If so, you should test the install flow on a clean machine (if possible) and write up the steps in a README. If this is not possible, the configuration files and assets should probably be removed.

2024-04-02 22:05 UTC, ash-teach commented
I think you've made some unintentional commits, but it is very difficult to say without there being any actual documentation in your submission. 

Please review and provide appropriate documentation (README.md, or comments, or both) so that your code and intention can be well-understood.

2024-04-04 13:43 UTC, Suhail0206327 commented
I have updated the readme file for better understanding of this repository

2024-04-15 17:57 UTC, ash-teach commented on README.md
> +
These comments don't really belong in the main README.md file. You could include them in your RRJ so that I know what you've done.

2024-04-15 17:58 UTC, ash-teach commented
I won't merge this because there are still too many errors in the PR: There are excess files, and some files that should not have been touched were edited. The work will remain, so there is a record of it, but it can't be merged as-is.

2024-04-15 17:58 UTC, closed without merging