Add java code implementation example of template pattern
nic-dgl104-winter-2024/pattern-library pull request #90
Opened 2024-03-26 23:06 UTC by Jessica-Pelletier

2024-03-27 08:40 UTC, abhiram-shaji commented
Hi Jessica, this looks pretty impressive and well explained. However, I would like to point out an issue with your package name. In Java, package names are written in all lower case to avoid conflict with the names of classes or interfaces. Also, I think you named it 'observal' instead of 'template' by mistake.

2024-03-27 18:49 UTC, Jessica-Pelletier commented
Hi Abhiram! 
Thanks for looking this over for me! I see these issues now. The package name auto filled for me because of the file structure.  Do you think it makes sense to simply change the package name from patterns.Behavioral.Observal.Java -> patterns.behavior.template.java?  I may have to look into this further.

2024-03-28 00:02 UTC, abhiram-shaji commented
> Thanks for looking this over for me! I see these issues now. The package name auto filled for me because of the file structure. Do you think it makes sense to simply change the package name from patterns.Behavioral.Observal.Java -> patterns.behavior.template.java? I may have to look into this further.

That definitely seem to be more suitable package name

2024-04-03 18:57 UTC, ash-teach requested changes

2024-04-03 18:57 UTC, ash-teach commented on patterns/Behavioral/Observal/Java/template.java
> +        System.out.println("Processing file data");
These `println` statements in `main` are probably not necessary, given that there is plenty of output already.

2024-04-03 18:57 UTC, ash-teach commented on patterns/Behavioral/Observal/Java/template.java
> +
Some typos: "tailored" and "**F**ileDataProcessor"

2024-04-03 18:57 UTC, ash-teach commented on patterns/Behavioral/Observal/Java/template.java
> + */
If you have used any external resources, could you please supply them as references here as well?

2024-04-03 18:57 UTC, ash-teach commented
Great work, @Jessica-Pelletier. I've noted a couple minor fixes above, if you can address them.

2024-04-03 22:24 UTC, Jessica-Pelletier commented
Changes have been made ! I got a little confused in the process of pushing my branch of my fork. Hopefully it's all good.

2024-04-16 16:27 UTC, merged